import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { ENV } from '../config/env';
import { Product } from '../models/Product';
import { LocationZone } from '../models/LocationZone';
import { Admin } from '../models/Admin';
import { Gallery } from '../models/Gallery';
import { BusinessInfo } from '../models/BusinessInfo';

const seedDatabase = async () => {
  try {
    console.log('Connecting to MongoDB for seeding...');
    await mongoose.connect(ENV.MONGODB_URI);
    console.log('Connected to MongoDB!');

    // 1. Clear existing seed collections
    await Promise.all([
      Product.deleteMany({}),
      LocationZone.deleteMany({}),
      Admin.deleteMany({}),
      Gallery.deleteMany({}),
      BusinessInfo.deleteMany({}),
    ]);
    console.log('Cleared existing data.');

    // 2. Insert Location Zones
    const zones = [
      {
        zoneKey: 'himachal',
        displayName: 'Himachal Pradesh',
        nepaliDisplayName: 'हिमाचल प्रदेश',
        states: ['Himachal Pradesh', 'HP'],
        cities: ['Kullu', 'Manali', 'Shimla', 'Dharamshala', 'Mandi', 'Solan', 'Kangra'],
        pincodePrefixes: ['17'],
        description: 'Local Himalayan Zone - Fast Direct Handover & Express Delivery',
        deliveryHighlights: 'Free Doorstep Delivery on all standard orders',
      },
      {
        zoneKey: 'delhiChandigarh',
        displayName: 'Delhi NCR & Chandigarh Tricity',
        nepaliDisplayName: 'दिल्ली तथा चण्डीगढ',
        states: ['Delhi', 'Chandigarh', 'Haryana', 'Punjab'],
        cities: ['Delhi', 'New Delhi', 'Chandigarh', 'Mohali', 'Panchkula', 'Gurugram', 'Noida', 'Faridabad'],
        pincodePrefixes: ['11', '16'],
        description: 'Direct Hub Express Transit - Next 24-48 Hours Dispatch',
        deliveryHighlights: 'Free Delivery on popular Chicken, Mutton & Dalle pickles',
      },
      {
        zoneKey: 'outside',
        displayName: 'All Other Indian States & Regions',
        nepaliDisplayName: 'भारतभर अन्य सबै स्थानहरू',
        states: ['Maharashtra', 'Karnataka', 'West Bengal', 'Uttar Pradesh', 'Bihar', 'Rajasthan', 'Gujarat', 'Tamil Nadu', 'Assam', 'Other'],
        cities: ['Mumbai', 'Bengaluru', 'Kolkata', 'Pune', 'Jaipur', 'Lucknow', 'Patna', 'Guwahati', 'Hyderabad', 'Chennai'],
        pincodePrefixes: [],
        description: 'Pan-India Express Airtight Courier Packaging',
        deliveryHighlights: 'Flat courier rates. Free Courier Delivery on 3kg+ Chicken & Dalle bulk orders!',
      },
    ];
    await LocationZone.insertMany(zones);
    console.log('Location Zones seeded.');

    // 3. Insert Authentic Nepali Pickles
    const products = [
      {
        name: 'Chicken Pickle',
        nepaliName: 'कुखुराको अचार',
        slug: 'chicken-pickle',
        category: 'non-veg',
        vegType: 'non-veg',
        description: 'Signature tender chicken pieces slow-cooked in pure cold-pressed mustard oil, infused with traditional Nepali spices, ginger, garlic, Timur, and roasted fenugreek. Rich, savory, and bursting with authentic Himalayan flavor.',
        shortDescription: 'Tender chicken slow-cooked in pure mustard oil and authentic Nepali mountain spices.',
        ingredients: ['Boneless Chicken', 'Pure Mustard Oil', 'Timur (Nepali Peppercorn)', 'Garlic', 'Ginger', 'Fenugreek', 'Cumin', 'Turmeric', 'Chili', 'Salt', 'Vinegar'],
        images: ['/images/achar/chicken-achar.png', '/images/gallery/table-pickles.jpg'],
        primaryImage: '/images/achar/chicken-achar.png',
        availableSizes: ['500g', '1kg', '2kg', '3kg+'],
        startingPrice: 1200,
        isAvailable: true,
        isFeatured: true,
        badge: 'Bestseller Non-Veg',
        displayOrder: 1,
        pricingRules: {
          himachal: { basePricePerKg: 1200, freeDelivery: true, notes: '₹1,200/kg (Delivery Free)' },
          delhiChandigarh: { basePricePerKg: 1300, freeDelivery: true, notes: '₹1,300/kg (Delivery Free)' },
          outside: { tier1KgPrice: 1800, tier3KgPrice: 3600, freeDeliveryThresholdKg: 3, notes: '1 kg: ₹1,800 incl. delivery | 3 kg+: ₹3,600 (Free Delivery)' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Mutton Pickle',
        nepaliName: 'मटन अचार',
        slug: 'mutton-pickle',
        category: 'non-veg',
        vegType: 'non-veg',
        description: 'Premium tender Himalayan goat mutton meat, cured and spiced following ancestral Nepali culinary recipes. Cooked to mouth-melting perfection in robust mustard oil and traditional whole spices.',
        shortDescription: 'Premium succulent goat meat cured with aromatic Himalayan spices and pure mustard oil.',
        ingredients: ['Prime Goat Mutton Meat', 'Cold-Pressed Mustard Oil', 'Himalayan Timur', 'Crushed Garlic', 'Ginger', 'Roasted Cumin', 'Mustard Seeds', 'Kashmiri Chili', 'Nepali Spices', 'Salt'],
        images: ['/images/achar/mutton-achar.png', '/images/gallery/packaged-assortment.jpg'],
        primaryImage: '/images/achar/mutton-achar.png',
        availableSizes: ['500g', '1kg', '2kg', '3kg+'],
        startingPrice: 2000,
        isAvailable: true,
        isFeatured: true,
        badge: 'Royal Himalayan Feast',
        displayOrder: 2,
        pricingRules: {
          himachal: { basePricePerKg: 2000, freeDelivery: true, notes: '₹2,000/kg (Delivery Free)' },
          delhiChandigarh: { basePricePerKg: 2200, freeDelivery: true, notes: '₹2,200/kg (Delivery Free)' },
          outside: { tier1KgPrice: 2600, basePricePerKg: 2200, courierPerKg: 230, notes: '1 kg: ₹2,600 incl. delivery | 3 kg+: ₹2,200/kg + ₹230/kg courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Fish Pickle',
        nepaliName: 'माछा को अचार',
        slug: 'fish-pickle',
        category: 'non-veg',
        vegType: 'non-veg',
        description: 'Crisp fried boneless fish chunks steeped in aromatic spiced mustard gravy with tangy mountain citrus and ginger-garlic paste. A rare and exquisite treat for fish lovers.',
        shortDescription: 'Delicate fish bites infused with tangy Himalayan citrus and aromatic spices.',
        ingredients: ['Selected Boneless Fish', 'Mustard Oil', 'Garlic', 'Ginger', 'Lemon Juice', 'Timur', 'Coriander Seeds', 'Methi Seeds', 'Red Chili', 'Salt'],
        images: ['/images/achar/fish-achar.jpg', '/images/gallery/shelf-jars-1.jpg'],
        primaryImage: '/images/achar/fish-achar.jpg',
        availableSizes: ['500g', '1kg', '2kg', '3kg+'],
        startingPrice: 1400,
        isAvailable: true,
        isFeatured: true,
        badge: 'Fresh River Flavor',
        displayOrder: 3,
        pricingRules: {
          himachal: { basePricePerKg: 1400, freeDelivery: true, notes: '₹1,400/kg (Delivery Free)' },
          delhiChandigarh: { basePricePerKg: 1400, freeDelivery: true, notes: '₹1,400/kg (Delivery Free)' },
          outside: { tier1KgPrice: 1800, basePricePerKg: 1400, courierPerKg: 230, notes: '1 kg: ₹1,800 incl. delivery | 3 kg+: ₹1,400/kg + ₹230/kg courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Dalle Khursani Pickle',
        nepaliName: 'डल्ले खुर्सानीको अचार',
        slug: 'dalle-khursani',
        category: 'spicy-special',
        vegType: 'veg',
        description: 'The world-famous red round cherry pepper from the hills of Nepal & Sikkim. Known for its explosive fiery punch combined with intoxicating aroma, preserved in mustard oil and fenugreek seeds.',
        shortDescription: 'Legendary round cherry peppers (दुनिया की सबसे तीखी गोल मिर्च) packed with fiery flavor.',
        ingredients: ['Organic Dalle Khursani Peppers', 'Pure Mustard Oil', 'Yellow Mustard Powder (Rai Dal)', 'Methi Seeds', 'Turmeric', 'Rock Salt', 'Himalayan Spices'],
        images: ['/images/achar/dalle-khursani.jpg', '/images/gallery/jar-closeup-2.jpg'],
        primaryImage: '/images/achar/dalle-khursani.jpg',
        availableSizes: ['250g', '500g', '1kg', '2kg', '3kg+'],
        startingPrice: 1000,
        isAvailable: true,
        isFeatured: true,
        badge: 'World Famous Fiery Hot',
        displayOrder: 4,
        pricingRules: {
          himachal: { basePricePerKg: 1000, freeDelivery: true, notes: '₹1,000/kg (Delivery Free)' },
          delhiChandigarh: { basePricePerKg: 1100, freeDelivery: true, notes: '₹1,100/kg (Delivery Free)' },
          outside: { tier1KgPrice: 1500, tier3KgPrice: 3000, freeDeliveryThresholdKg: 3, notes: '1 kg: ₹1,500 incl. delivery | 3 kg: ₹3,000 (Free Delivery)' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Raw Garlic Pickle',
        nepaliName: 'काँचो लसुनको अचार',
        slug: 'raw-garlic',
        category: 'veg',
        vegType: 'veg',
        description: 'Fresh, juicy mountain garlic cloves seasoned raw in cold-pressed mustard oil, cracked coriander, red chili, and rock salt. Enhances digestion and adds a zesty punch to daily meals.',
        shortDescription: 'Fresh whole garlic cloves cured with rich spices and pure mustard oil.',
        ingredients: ['Fresh Mountain Garlic Cloves', 'Mustard Oil', 'Coarse Mustard Seeds', 'Cumin', 'Red Chili Flakes', 'Turmeric', 'Rock Salt', 'Citric Blend'],
        images: ['/images/achar/raw-garlic-achar.jpg', '/images/achar/garlic-achar.jpg'],
        primaryImage: '/images/achar/raw-garlic-achar.jpg',
        availableSizes: ['500g', '1kg', '2kg', '3kg'],
        startingPrice: 600,
        isAvailable: true,
        isFeatured: false,
        badge: 'Immunity & Digestion Booster',
        displayOrder: 5,
        pricingRules: {
          himachal: { basePricePerKg: 600, freeDelivery: true, notes: '₹600/kg (Delivery Free)' },
          delhiChandigarh: { basePricePerKg: 600, freeDelivery: true, notes: '₹600/kg (Delivery Free)' },
          outside: { basePricePerKg: 600, courierPerKg: 200, notes: '₹600/kg + ₹200/kg Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Fried / Dried Garlic Pickle',
        nepaliName: 'सुकेको / फ्राई लसुनको अचार',
        slug: 'fried-garlic',
        category: 'veg',
        vegType: 'veg',
        description: 'Crisp, golden roasted dried garlic cloves tossed in spiced mustard blend and Himalayan herbs. Offers a rich, savory nutty bite without the raw sharpness.',
        shortDescription: 'Crispy roasted garlic cloves seasoned in aromatic mountain spice blends.',
        ingredients: ['Sun-Dried Fried Garlic', 'Pure Mustard Oil', 'Roasted Fenugreek', 'Coriander', 'Red Chili', 'Black Salt', 'Lemon Essence'],
        images: ['/images/achar/fried-garlic-achar.jpg', '/images/achar/garlic-achar.jpg'],
        primaryImage: '/images/achar/fried-garlic-achar.jpg',
        availableSizes: ['500g', '1kg', '2kg', '3kg'],
        startingPrice: 700,
        isAvailable: true,
        isFeatured: false,
        badge: 'Golden Crispy Savor',
        displayOrder: 6,
        pricingRules: {
          himachal: { basePricePerKg: 700, freeDelivery: true, notes: '₹700/kg (Delivery Free)' },
          delhiChandigarh: { basePricePerKg: 800, freeDelivery: true, notes: '₹800/kg (Delivery Free)' },
          outside: { basePricePerKg: 800, courierPerKg: 200, notes: '₹800/kg + ₹200/kg Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Gundruk Pickle',
        nepaliName: 'गुन्द्रुक को अचार',
        slug: 'gundruk-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Nepal’s most iconic heritage food. Naturally fermented leafy greens (mustard, radish & rayo leaves) dried in Himalayan sun and pickled with roasted sesame, timur, green chilies, and cold mustard oil.',
        shortDescription: 'National pride of Nepal — naturally fermented sun-dried leafy greens with roasted sesame.',
        ingredients: ['Fermented Gundruk Leaves', 'Roasted White Sesame (Til)', 'Mustard Oil', 'Timur Peppercorn', 'Green Chili Paste', 'Garlic', 'Himalayan Salt'],
        images: ['/images/achar/gundruk-achar.png', '/images/banner/hero-banner.png'],
        primaryImage: '/images/achar/gundruk-achar.png',
        availableSizes: ['400g', '800g', '1kg+'],
        startingPrice: 299,
        isAvailable: true,
        isFeatured: true,
        badge: 'Nepali Cultural Heritage',
        displayOrder: 7,
        pricingRules: {
          himachal: { basePricePerKg: 650, freeDelivery: true, notes: '₹299 (400g) / ₹650/kg' },
          delhiChandigarh: { basePricePerKg: 700, freeDelivery: true, notes: '₹299 (400g) / ₹700/kg' },
          outside: { basePricePerKg: 700, courierPerKg: 150, notes: '₹700/kg + Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Timur Pickle',
        nepaliName: 'टिमुर को अचार',
        slug: 'timur-pickle',
        category: 'spicy-special',
        vegType: 'veg',
        description: 'Handpicked wild Himalayan Szechuan peppercorns (Timur) known for their citrus aroma and unique tongue-tingling numbing sensation, blended into a robust spicy relish.',
        shortDescription: 'Tingling Himalayan Szechuan peppercorns with citrusy aroma and fiery depth.',
        ingredients: ['Wild Himalayan Timur', 'Mustard Oil', 'Garlic Paste', 'Dry Roasted Red Chilies', 'Cumin', 'Rock Salt', 'Lime Juice'],
        images: ['/images/achar/timur-achar.png', '/images/banner/promo-banner.png'],
        primaryImage: '/images/achar/timur-achar.png',
        availableSizes: ['400g', '800g', '1kg+'],
        startingPrice: 299,
        isAvailable: true,
        isFeatured: true,
        badge: 'Wild Mountain Aroma',
        displayOrder: 8,
        pricingRules: {
          himachal: { basePricePerKg: 700, freeDelivery: true, notes: '₹299 (400g)' },
          delhiChandigarh: { basePricePerKg: 750, freeDelivery: true, notes: '₹299 (400g)' },
          outside: { basePricePerKg: 750, courierPerKg: 150, notes: '₹750/kg + Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Tama Pickle (Bamboo Shoot)',
        nepaliName: 'तामा को अचार',
        slug: 'tama-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Tender young mountain bamboo shoots fermented and tempered with mustard seeds, fenugreek, and crushed chilies. A quintessential delicacy of the Nepali hills.',
        shortDescription: 'Fermented tender mountain bamboo shoots with rich traditional spices.',
        ingredients: ['Fermented Bamboo Shoots (Tama)', 'Cold-Pressed Mustard Oil', 'Fenugreek', 'Mustard Seeds', 'Turmeric', 'Red Chili Powder', 'Salt'],
        images: ['/images/achar/tama-achar.png'],
        primaryImage: '/images/achar/tama-achar.png',
        availableSizes: ['400g', '1kg'],
        startingPrice: 299,
        isAvailable: true,
        isFeatured: false,
        badge: 'Hill Specialty',
        displayOrder: 9,
        pricingRules: {
          himachal: { basePricePerKg: 650, freeDelivery: true, notes: '₹299 (400g)' },
          delhiChandigarh: { basePricePerKg: 700, freeDelivery: true, notes: '₹299 (400g)' },
          outside: { basePricePerKg: 700, courierPerKg: 150, notes: '₹700/kg + Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Lapsi Pickle (Hog Plum)',
        nepaliName: 'लप्सी को अचार',
        slug: 'lapsi-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Native Nepali wild plum fruit (Choerospondias axillaris) boiled, pulp extracted, and simmered into a mouthwatering sweet, sour, and mildly spiced gourmet pickle.',
        shortDescription: 'Sweet and tangy wild Nepali plum cooked to sticky spiced perfection.',
        ingredients: ['Pure Nepali Lapsi Pulp', 'Jaggery / Sugar', 'Mustard Oil', 'Roasted Cumin', 'Red Chili Flakes', 'Black Salt', 'Timur Hint'],
        images: ['/images/achar/lapsi-achar.png'],
        primaryImage: '/images/achar/lapsi-achar.png',
        availableSizes: ['400g', '1kg'],
        startingPrice: 299,
        isAvailable: true,
        isFeatured: false,
        badge: 'Sweet & Tangy Delicacy',
        displayOrder: 10,
        pricingRules: {
          himachal: { basePricePerKg: 650, freeDelivery: true, notes: '₹299 (400g)' },
          delhiChandigarh: { basePricePerKg: 700, freeDelivery: true, notes: '₹299 (400g)' },
          outside: { basePricePerKg: 700, courierPerKg: 150, notes: '₹700/kg + Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Khalpi Pickle (Cucumber)',
        nepaliName: 'खल्पि / काक्रो को अचार',
        slug: 'khalpi-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Sun-cured mature mountain cucumbers salted, dried, and preserved in pungent yellow mustard seeds, turmeric, and mustard oil. Crunch that reminds you of home.',
        shortDescription: 'Sun-dried traditional hill cucumbers marinated in pungent mustard gravy.',
        ingredients: ['Sun-Dried Mountain Cucumbers', 'Crushed Yellow Mustard (Rai)', 'Cold-Pressed Mustard Oil', 'Fenugreek', 'Turmeric', 'Chili Flakes', 'Salt'],
        images: ['/images/achar/khalpi-achar.png'],
        primaryImage: '/images/achar/khalpi-achar.png',
        availableSizes: ['400g', '1kg'],
        startingPrice: 299,
        isAvailable: true,
        isFeatured: false,
        badge: 'Traditional Sun-Cured',
        displayOrder: 11,
        pricingRules: {
          himachal: { basePricePerKg: 600, freeDelivery: true, notes: '₹299 (400g)' },
          delhiChandigarh: { basePricePerKg: 650, freeDelivery: true, notes: '₹299 (400g)' },
          outside: { basePricePerKg: 650, courierPerKg: 150, notes: '₹650/kg + Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Til Pickle (Roasted Sesame)',
        nepaliName: 'तिल को अचार',
        slug: 'til-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Stone-ground roasted white and black sesame seeds blended with boiled mountain potatoes, fresh lime, timur, and fiery green chilies. Rich and velvety texture.',
        shortDescription: 'Velvety stone-ground roasted sesame paste with zesty Himalayan seasonings.',
        ingredients: ['Slow-Roasted Sesame Seeds (Til)', 'Mustard Oil', 'Timur Powder', 'Lemon Juice', 'Green Chili Paste', 'Garlic', 'Himalayan Rock Salt'],
        images: ['/images/achar/til-achar.jpg'],
        primaryImage: '/images/achar/til-achar.jpg',
        availableSizes: ['400g', '1kg'],
        startingPrice: 299,
        isAvailable: true,
        isFeatured: false,
        badge: 'Aromatic & Velvety',
        displayOrder: 12,
        pricingRules: {
          himachal: { basePricePerKg: 650, freeDelivery: true, notes: '₹299 (400g)' },
          delhiChandigarh: { basePricePerKg: 700, freeDelivery: true, notes: '₹299 (400g)' },
          outside: { basePricePerKg: 700, courierPerKg: 150, notes: '₹700/kg + Courier' },
          priceOnRequest: false,
        },
      },
      {
        name: 'Radish Pickle',
        nepaliName: 'मुला को अचार',
        slug: 'radish-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Sun-dried crisp radish strips tossed with ground mustard seeds, methi, red chilies, and pure mustard oil. The everyday comfort pickle for Dal-Bhat.',
        shortDescription: 'Sun-dried crisp radish with pungent mustard and fenugreek.',
        ingredients: ['Sun-Dried Mountain Radish', 'Mustard Oil', 'Mustard Seeds', 'Fenugreek Seeds', 'Turmeric', 'Chili', 'Salt'],
        images: ['/images/achar/radish-achar.jpg'],
        primaryImage: '/images/achar/radish-achar.jpg',
        availableSizes: ['500g', '1kg'],
        startingPrice: 500,
        isAvailable: true,
        isFeatured: false,
        badge: 'Daily Classic',
        displayOrder: 13,
        pricingRules: {
          himachal: { basePricePerKg: 500, freeDelivery: true },
          delhiChandigarh: { basePricePerKg: 550, freeDelivery: true },
          outside: { basePricePerKg: 550, courierPerKg: 150 },
          priceOnRequest: false,
        },
      },
      {
        name: 'Mango Pickle',
        nepaliName: 'आम को अचार',
        slug: 'mango-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Raw mountain green mango pieces marinated in traditional whole and ground spices, preserved under natural mountain sunlight in pure mustard oil.',
        shortDescription: 'Zesty green raw mango steeped in golden mustard oil.',
        ingredients: ['Raw Mango Cuts', 'Cold-Pressed Mustard Oil', 'Kalonji', 'Saunf', 'Fenugreek', 'Red Chili', 'Salt'],
        images: ['/images/achar/mango-achar.jpg'],
        primaryImage: '/images/achar/mango-achar.jpg',
        availableSizes: ['500g', '1kg'],
        startingPrice: 500,
        isAvailable: true,
        isFeatured: false,
        badge: 'Zesty Heritage',
        displayOrder: 14,
        pricingRules: {
          himachal: { basePricePerKg: 500, freeDelivery: true },
          delhiChandigarh: { basePricePerKg: 550, freeDelivery: true },
          outside: { basePricePerKg: 550, courierPerKg: 150 },
          priceOnRequest: false,
        },
      },
      {
        name: 'Lemon Pickle',
        nepaliName: 'निम्बु को अचार',
        slug: 'lemon-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'Juicy mountain kagazi lemons aged with carom seeds (ajwain), black salt, and mild spices. Soothing for the throat and appetizing for every palate.',
        shortDescription: 'Aged juicy mountain lemons with ajwain and Himalayan rock salt.',
        ingredients: ['Fresh Mountain Lemons', 'Ajwain (Carom Seeds)', 'Black Salt', 'Turmeric', 'Red Chili', 'Mustard Oil (minimal)'],
        images: ['/images/achar/lemon-achar.jpg'],
        primaryImage: '/images/achar/lemon-achar.jpg',
        availableSizes: ['500g', '1kg'],
        startingPrice: 500,
        isAvailable: true,
        isFeatured: false,
        badge: 'Tangy Digestive Classic',
        displayOrder: 15,
        pricingRules: {
          himachal: { basePricePerKg: 500, freeDelivery: true },
          delhiChandigarh: { basePricePerKg: 550, freeDelivery: true },
          outside: { basePricePerKg: 550, courierPerKg: 150 },
          priceOnRequest: false,
        },
      },
      {
        name: 'Mixed Vegetable Pickle',
        nepaliName: 'मिक्स वेज अचार',
        slug: 'mixed-veg-pickle',
        category: 'veg',
        vegType: 'veg',
        description: 'A colorful medley of cauliflower, carrots, peas, and green chilies crunchily seasoned in handcrafted Nepali spice paste.',
        shortDescription: 'Crunchy farm vegetables tossed in vibrant Nepali spices.',
        ingredients: ['Cauliflower', 'Carrot', 'Green Chili', 'Ginger', 'Mustard Oil', 'Mustard Seeds', 'Salt', 'Spices'],
        images: ['/images/achar/mixed-achar.jpg'],
        primaryImage: '/images/achar/mixed-achar.jpg',
        availableSizes: ['500g', '1kg'],
        startingPrice: 500,
        isAvailable: true,
        isFeatured: false,
        badge: 'Farm Fresh Medley',
        displayOrder: 16,
        pricingRules: {
          himachal: { basePricePerKg: 500, freeDelivery: true },
          delhiChandigarh: { basePricePerKg: 550, freeDelivery: true },
          outside: { basePricePerKg: 550, courierPerKg: 150 },
          priceOnRequest: false,
        },
      },
    ];

    await Product.insertMany(products);
    console.log(`Inserted ${products.length} authentic Nepali products.`);

    // 4. Insert Default Admin
    const salt = await bcrypt.genSalt(10);
    const passwordHash = await bcrypt.hash('admin12345', salt);
    await Admin.create({
      name: 'Sunita Kathayat & Tilak Sijapati',
      email: 'admin@everestachar.com',
      passwordHash,
      role: 'superadmin',
    });
    console.log('Default Admin created: admin@everestachar.com / admin12345');

    // 5. Insert Gallery Items
    const galleryItems = [
      {
        title: 'Authentic Mountain Pickles Shelf Display',
        nepaliTitle: 'ताजा अचारहरूको भण्डारण',
        image: '/images/gallery/shelf-jars-1.jpg',
        category: 'behind_the_scenes',
        description: 'Freshly prepared batches arranged on aging shelves in Kullu-Manali.',
        displayOrder: 1,
        featured: true,
      },
      {
        title: 'Our Signature Non-Veg & Veg Jars',
        nepaliTitle: 'शाकाहारी तथा मांसाहारी अचारहरू',
        image: '/images/gallery/packaged-assortment.jpg',
        category: 'packaging',
        description: 'Glass jars labeled with love, showing natural mustard oil clarity.',
        displayOrder: 2,
        featured: true,
      },
      {
        title: 'Full Batch Storage & Inspection',
        nepaliTitle: 'अचार उत्पादन तथा गुणस्तर परीक्षण',
        image: '/images/gallery/shelf-jars-full.jpg',
        category: 'behind_the_scenes',
        description: 'Rigorous hygiene and careful packing of every batch.',
        displayOrder: 3,
        featured: true,
      },
      {
        title: 'Everest Official Packaging Label & Standards',
        nepaliTitle: 'एभरेस्ट नेपाली अचार प्याकेजिङ',
        image: '/images/gallery/official-packaging.jpg',
        category: 'packaging',
        description: 'Founder Sunita Kathayat with full product details and recipe heritage.',
        displayOrder: 4,
        featured: true,
      },
      {
        title: 'Freshly Tempered Spices & Pickles on Table',
        nepaliTitle: 'टेबुलमा सजिएका ताजा अचारहरू',
        image: '/images/gallery/table-pickles.jpg',
        category: 'all',
        description: 'Pure mustard oil and whole red chilies bringing appetizing vibrancy.',
        displayOrder: 5,
        featured: true,
      },
      {
        title: 'Hand-Packed Artisan Jars for Dispatch',
        nepaliTitle: 'सुरक्षित डेलिभरी प्याकिङ',
        image: '/images/gallery/jar-closeup-2.jpg',
        category: 'packaging',
        description: 'Airtight double sealed caps to guarantee zero leakage during transit.',
        displayOrder: 6,
        featured: false,
      },
      {
        title: 'Himalayan Spices & Traditional Mountain Flavors',
        nepaliTitle: 'हिमाली मसला तथा परम्परागत स्वाद',
        image: '/images/banner/mountain-spice-banner.png',
        category: 'culture',
        description: 'Timur, Mustard seeds, and mountain herbs sourced directly from high altitudes.',
        displayOrder: 7,
        featured: true,
      },
    ];
    await Gallery.insertMany(galleryItems);
    console.log(`Inserted ${galleryItems.length} gallery media items.`);

    // 6. Insert Business Info
    await BusinessInfo.create({
      brandName: 'EVEREST नेपाली अचार',
      brandNepaliName: 'एभरेस्ट नेपाली अचार',
      tagline: 'नेपाल की परंपरा, स्वाद में बेजोड़',
      nepaliTagline: 'स्वाद नेपाल का, भरोसा हमारा',
      owners: 'Sunita Kathayat & Tilak Sijapati',
      phone: '+91 79915 02810',
      whatsapp: '+91 79915 02810',
      address: {
        town: 'Kullu, Manali',
        district: 'Kullu',
        state: 'Himachal Pradesh',
        pincode: '175131',
        country: 'India',
      },
      faqs: [
        {
          question: 'Do you deliver outside Himachal Pradesh?',
          nepaliQuestion: 'के तपाईं हिमाचल प्रदेश बाहिर पनि डेलिभरी गर्नुहुन्छ?',
          answer: 'Yes! We deliver across India including Delhi NCR, Chandigarh Tricity, Punjab, Mumbai, Bangalore, and all other states via express courier.',
          nepaliAnswer: 'हजुर! हामी दिल्ली, चण्डीगढ र भारतभर कुरियर मार्फत डेलिभरी गर्छौं।',
          category: 'Delivery',
        },
        {
          question: 'How can I place an order?',
          nepaliQuestion: 'मैले अर्डर कसरी गर्ने?',
          answer: 'You can select your favorite pickle on this website, choose your location, get the exact price, and submit the booking. You will instantly receive a WhatsApp confirmation link to connect with our team.',
          nepaliAnswer: 'वेबसाइटमा आफ्नो मनपर्ने अचार रोज्नुहोस् र अर्डर गर्नुहोस् वा ह्वाट्सएप मार्फत सिधै सम्पर्क गर्नुहोस्।',
          category: 'Ordering',
        },
        {
          question: 'Are there discounts or free delivery on bulk orders?',
          nepaliQuestion: 'के ठूलो अर्डरमा फ्री डेलिभरी पाइन्छ?',
          answer: 'Yes! For example, 3kg or more Chicken Pickle or Dalle Khursani Pickle outside Delhi comes with FREE courier delivery and bulk discount pricing.',
          nepaliAnswer: 'हजुर, ३ केजी वा सोभन्दा बढी अर्डर गर्दा फ्री डेलिभरी र विशेष छुट उपलब्ध छ।',
          category: 'Pricing',
        },
        {
          question: 'Who are the founders of Everest Nepali Achar?',
          nepaliQuestion: 'एभरेस्ट नेपाली अचारका संस्थापक को हुन्?',
          answer: 'Everest Nepali Achar is lovingly founded and run by Sunita Kathayat & Tilak Sijapati based in Kullu-Manali, Himachal Pradesh, carrying forward authentic Nepali Himalayan recipes.',
          nepaliAnswer: 'एभरेस्ट नेपाली अचार सुनिता कठायत र तिलक सिजापति द्वारा कुल्लु-मनालीमा सञ्चालन गरिन्छ।',
          category: 'About',
        },
      ],
    });
    console.log('Business Info seeded.');

    console.log('🎉 Seeding successfully completed!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
};

seedDatabase();
